// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gokrqmykzovxqaoanapu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdva3JxbXlrem92eHFhb2FuYXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzY3NzUsImV4cCI6MjA1OTYxMjc3NX0.T8ItZlFLl-aUB-VVR5tuclKc3lmxT2mtSyWRtrmylMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);